
namespace Admin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Admin.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string @action {
                                get {
                                    return ResourceManager.GetString("action", resourceCulture);
                                }
                            }
                            
public static string alerttemplates {
                                get {
                                    return ResourceManager.GetString("alerttemplates", resourceCulture);
                                }
                            }
                            
public static string alerttemplates_alertcarboncopyto {
                                get {
                                    return ResourceManager.GetString("alerttemplates_alertcarboncopyto", resourceCulture);
                                }
                            }
                            
public static string alerttemplates_alertcontent {
                                get {
                                    return ResourceManager.GetString("alerttemplates_alertcontent", resourceCulture);
                                }
                            }
                            
public static string alerttemplates_alertcopyto {
                                get {
                                    return ResourceManager.GetString("alerttemplates_alertcopyto", resourceCulture);
                                }
                            }
                            
public static string alerttemplates_alertsubject {
                                get {
                                    return ResourceManager.GetString("alerttemplates_alertsubject", resourceCulture);
                                }
                            }
                            
public static string alerttemplates_alerttype {
                                get {
                                    return ResourceManager.GetString("alerttemplates_alerttype", resourceCulture);
                                }
                            }
                            
public static string alerttemplates_entityaction {
                                get {
                                    return ResourceManager.GetString("alerttemplates_entityaction", resourceCulture);
                                }
                            }
                            
public static string alerttemplates_entityname {
                                get {
                                    return ResourceManager.GetString("alerttemplates_entityname", resourceCulture);
                                }
                            }
                            
public static string alerttemplates_sendasbatch {
                                get {
                                    return ResourceManager.GetString("alerttemplates_sendasbatch", resourceCulture);
                                }
                            }
                            
public static string alerttemplateslist {
                                get {
                                    return ResourceManager.GetString("alerttemplateslist", resourceCulture);
                                }
                            }
                            
public static string alloweddevices {
                                get {
                                    return ResourceManager.GetString("alloweddevices", resourceCulture);
                                }
                            }
                            
public static string appadmin {
                                get {
                                    return ResourceManager.GetString("appadmin", resourceCulture);
                                }
                            }
                            
public static string apply {
                                get {
                                    return ResourceManager.GetString("apply", resourceCulture);
                                }
                            }
                            
public static string authenticate {
                                get {
                                    return ResourceManager.GetString("authenticate", resourceCulture);
                                }
                            }
                            
public static string back {
                                get {
                                    return ResourceManager.GetString("back", resourceCulture);
                                }
                            }
                            
public static string cancel {
                                get {
                                    return ResourceManager.GetString("cancel", resourceCulture);
                                }
                            }
                            
public static string changepassword {
                                get {
                                    return ResourceManager.GetString("changepassword", resourceCulture);
                                }
                            }
                            
public static string clone {
                                get {
                                    return ResourceManager.GetString("clone", resourceCulture);
                                }
                            }
                            
public static string createalerttemplates {
                                get {
                                    return ResourceManager.GetString("createalerttemplates", resourceCulture);
                                }
                            }
                            
public static string createmaillog {
                                get {
                                    return ResourceManager.GetString("createmaillog", resourceCulture);
                                }
                            }
                            
public static string createretailersinc {
                                get {
                                    return ResourceManager.GetString("createretailersinc", resourceCulture);
                                }
                            }
                            
public static string download {
                                get {
                                    return ResourceManager.GetString("download", resourceCulture);
                                }
                            }
                            
public static string environmentmanagement {
                                get {
                                    return ResourceManager.GetString("environmentmanagement", resourceCulture);
                                }
                            }
                            
public static string forgotpasswordcommon {
                                get {
                                    return ResourceManager.GetString("forgotpasswordcommon", resourceCulture);
                                }
                            }
                            
public static string @from {
                                get {
                                    return ResourceManager.GetString("from", resourceCulture);
                                }
                            }
                            
public static string @index {
                                get {
                                    return ResourceManager.GetString("index", resourceCulture);
                                }
                            }
                            
public static string listofuserprofiles {
                                get {
                                    return ResourceManager.GetString("listofuserprofiles", resourceCulture);
                                }
                            }
                            
public static string login {
                                get {
                                    return ResourceManager.GetString("login", resourceCulture);
                                }
                            }
                            
public static string logout {
                                get {
                                    return ResourceManager.GetString("logout", resourceCulture);
                                }
                            }
                            
public static string lookups {
                                get {
                                    return ResourceManager.GetString("lookups", resourceCulture);
                                }
                            }
                            
public static string maillogs {
                                get {
                                    return ResourceManager.GetString("maillogs", resourceCulture);
                                }
                            }
                            
public static string maillogs_entityid {
                                get {
                                    return ResourceManager.GetString("maillogs_entityid", resourceCulture);
                                }
                            }
                            
public static string maillogs_entityname {
                                get {
                                    return ResourceManager.GetString("maillogs_entityname", resourceCulture);
                                }
                            }
                            
public static string maillogs_issent {
                                get {
                                    return ResourceManager.GetString("maillogs_issent", resourceCulture);
                                }
                            }
                            
public static string maillogs_mailbody {
                                get {
                                    return ResourceManager.GetString("maillogs_mailbody", resourceCulture);
                                }
                            }
                            
public static string maillogs_mailfor {
                                get {
                                    return ResourceManager.GetString("maillogs_mailfor", resourceCulture);
                                }
                            }
                            
public static string maillogs_mailsubject {
                                get {
                                    return ResourceManager.GetString("maillogs_mailsubject", resourceCulture);
                                }
                            }
                            
public static string maillogs_mailto {
                                get {
                                    return ResourceManager.GetString("maillogs_mailto", resourceCulture);
                                }
                            }
                            
public static string maillogslist {
                                get {
                                    return ResourceManager.GetString("maillogslist", resourceCulture);
                                }
                            }
                            
public static string manageretailersinc {
                                get {
                                    return ResourceManager.GetString("manageretailersinc", resourceCulture);
                                }
                            }
                            
public static string manageroleauthorization {
                                get {
                                    return ResourceManager.GetString("manageroleauthorization", resourceCulture);
                                }
                            }
                            
public static string manageusers {
                                get {
                                    return ResourceManager.GetString("manageusers", resourceCulture);
                                }
                            }
                            
public static string platformadmin {
                                get {
                                    return ResourceManager.GetString("platformadmin", resourceCulture);
                                }
                            }
                            
public static string @print {
                                get {
                                    return ResourceManager.GetString("print", resourceCulture);
                                }
                            }
                            
public static string providertenantdisplayname {
                                get {
                                    return ResourceManager.GetString("providertenantdisplayname", resourceCulture);
                                }
                            }
                            
public static string registerprofile {
                                get {
                                    return ResourceManager.GetString("registerprofile", resourceCulture);
                                }
                            }
                            
public static string removealerttemplates {
                                get {
                                    return ResourceManager.GetString("removealerttemplates", resourceCulture);
                                }
                            }
                            
public static string removemaillog {
                                get {
                                    return ResourceManager.GetString("removemaillog", resourceCulture);
                                }
                            }
                            
public static string removeretailersinc {
                                get {
                                    return ResourceManager.GetString("removeretailersinc", resourceCulture);
                                }
                            }
                            
public static string retailersincadmin {
                                get {
                                    return ResourceManager.GetString("retailersincadmin", resourceCulture);
                                }
                            }
                            
public static string roles {
                                get {
                                    return ResourceManager.GetString("roles", resourceCulture);
                                }
                            }
                            
public static string roles_parentname {
                                get {
                                    return ResourceManager.GetString("roles_parentname", resourceCulture);
                                }
                            }
                            
public static string roles_rolegroupname {
                                get {
                                    return ResourceManager.GetString("roles_rolegroupname", resourceCulture);
                                }
                            }
                            
public static string roles_rolehierarchynumber {
                                get {
                                    return ResourceManager.GetString("roles_rolehierarchynumber", resourceCulture);
                                }
                            }
                            
public static string roles_rolename {
                                get {
                                    return ResourceManager.GetString("roles_rolename", resourceCulture);
                                }
                            }
                            
public static string @save {
                                get {
                                    return ResourceManager.GetString("save", resourceCulture);
                                }
                            }
                            
public static string savedraft {
                                get {
                                    return ResourceManager.GetString("savedraft", resourceCulture);
                                }
                            }
                            
public static string setupretailersinc {
                                get {
                                    return ResourceManager.GetString("setupretailersinc", resourceCulture);
                                }
                            }
                            
public static string setupretailersincusers {
                                get {
                                    return ResourceManager.GetString("setupretailersincusers", resourceCulture);
                                }
                            }
                            
public static string submit {
                                get {
                                    return ResourceManager.GetString("submit", resourceCulture);
                                }
                            }
                            
public static string suspendprofile {
                                get {
                                    return ResourceManager.GetString("suspendprofile", resourceCulture);
                                }
                            }
                            
public static string tenant {
                                get {
                                    return ResourceManager.GetString("tenant", resourceCulture);
                                }
                            }
                            
public static string tenant_emailid {
                                get {
                                    return ResourceManager.GetString("tenant_emailid", resourceCulture);
                                }
                            }
                            
public static string tenant_firstname {
                                get {
                                    return ResourceManager.GetString("tenant_firstname", resourceCulture);
                                }
                            }
                            
public static string tenant_lastname {
                                get {
                                    return ResourceManager.GetString("tenant_lastname", resourceCulture);
                                }
                            }
                            
public static string tenant_mobilenumber {
                                get {
                                    return ResourceManager.GetString("tenant_mobilenumber", resourceCulture);
                                }
                            }
                            
public static string tenant_passwordkey {
                                get {
                                    return ResourceManager.GetString("tenant_passwordkey", resourceCulture);
                                }
                            }
                            
public static string tenant_username {
                                get {
                                    return ResourceManager.GetString("tenant_username", resourceCulture);
                                }
                            }
                            
public static string tenant_userpassword {
                                get {
                                    return ResourceManager.GetString("tenant_userpassword", resourceCulture);
                                }
                            }
                            
public static string tenant_userrole {
                                get {
                                    return ResourceManager.GetString("tenant_userrole", resourceCulture);
                                }
                            }
                            
public static string tenantdisplayname {
                                get {
                                    return ResourceManager.GetString("tenantdisplayname", resourceCulture);
                                }
                            }
                            
public static string @to {
                                get {
                                    return ResourceManager.GetString("to", resourceCulture);
                                }
                            }
                            
public static string updatealerttemplates {
                                get {
                                    return ResourceManager.GetString("updatealerttemplates", resourceCulture);
                                }
                            }
                            
public static string updatemaillog {
                                get {
                                    return ResourceManager.GetString("updatemaillog", resourceCulture);
                                }
                            }
                            
public static string updateprofile {
                                get {
                                    return ResourceManager.GetString("updateprofile", resourceCulture);
                                }
                            }
                            
public static string updateretailersinc {
                                get {
                                    return ResourceManager.GetString("updateretailersinc", resourceCulture);
                                }
                            }
                            
public static string usermanagement {
                                get {
                                    return ResourceManager.GetString("usermanagement", resourceCulture);
                                }
                            }
                            
public static string users {
                                get {
                                    return ResourceManager.GetString("users", resourceCulture);
                                }
                            }
                            
public static string users_alloweddevices_deviceid {
                                get {
                                    return ResourceManager.GetString("users_alloweddevices_deviceid", resourceCulture);
                                }
                            }
                            
public static string users_alloweddevices_devicename {
                                get {
                                    return ResourceManager.GetString("users_alloweddevices_devicename", resourceCulture);
                                }
                            }
                            
public static string users_alloweddevices_notificationid {
                                get {
                                    return ResourceManager.GetString("users_alloweddevices_notificationid", resourceCulture);
                                }
                            }
                            
public static string users_emailid {
                                get {
                                    return ResourceManager.GetString("users_emailid", resourceCulture);
                                }
                            }
                            
public static string users_firstname {
                                get {
                                    return ResourceManager.GetString("users_firstname", resourceCulture);
                                }
                            }
                            
public static string users_lastname {
                                get {
                                    return ResourceManager.GetString("users_lastname", resourceCulture);
                                }
                            }
                            
public static string users_mobilenumber {
                                get {
                                    return ResourceManager.GetString("users_mobilenumber", resourceCulture);
                                }
                            }
                            
public static string users_passwordkey {
                                get {
                                    return ResourceManager.GetString("users_passwordkey", resourceCulture);
                                }
                            }
                            
public static string users_profilepicture {
                                get {
                                    return ResourceManager.GetString("users_profilepicture", resourceCulture);
                                }
                            }
                            
public static string users_username {
                                get {
                                    return ResourceManager.GetString("users_username", resourceCulture);
                                }
                            }
                            
public static string users_userpassword {
                                get {
                                    return ResourceManager.GetString("users_userpassword", resourceCulture);
                                }
                            }
                            
public static string users_userrole {
                                get {
                                    return ResourceManager.GetString("users_userrole", resourceCulture);
                                }
                            }
                            
public static string viewdetailsofretailersinc {
                                get {
                                    return ResourceManager.GetString("viewdetailsofretailersinc", resourceCulture);
                                }
                            }
                            
public static string viewdraft {
                                get {
                                    return ResourceManager.GetString("viewdraft", resourceCulture);
                                }
                            }
                            
public static string viewdraftlist {
                                get {
                                    return ResourceManager.GetString("viewdraftlist", resourceCulture);
                                }
                            }
                            
public static string viewlistofretailersinc {
                                get {
                                    return ResourceManager.GetString("viewlistofretailersinc", resourceCulture);
                                }
                            }
                            

    }
}

